In [1]:
import numpy as np
import torch

/home/sunshuo/miniconda3/envs/FinRL/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
np.array(torch.tensor([1,2,3]))

array([1, 2, 3])

In [3]:
np.array(np.array([1,2,3]))

array([1, 2, 3])

In [4]:
[[0]+[1]*24]

[[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [5]:
a=[1,2,3,4,5,6]

In [6]:
a[-2]

5

In [7]:
np.sum(np.abs(np.array([0.1,0.1,0.8])-np.array([0.1,0.2,0.7])))

0.2000000000000001

In [8]:
a=[1,2,3,4]
b=[[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9]]
import pandas as pd
df_date = pd.DataFrame(a)
df_date.columns = ['date']
df_weights = pd.DataFrame(b)
df_weights.columns = ["1","2"]

In [9]:
df_weights

1  2
0  1  2
1  2  3
2  3  4
3  4  5
4  5  6
5  6  7
6  7  8
7  8  9

In [10]:
df_date

date
0     1
1     2
2     3
3     4

In [11]:
df_date.date.values

array([1, 2, 3, 4])

In [12]:
A=pd.DataFrame()
A["q"]=[1,2,3,4]
A

q
0  1
1  2
2  3
3  4

In [13]:
a={"1":1,"2":2}
b={"3":3}
c={"4":4}
b.update(a)
b

{'3': 3, '1': 1, '2': 2}

In [14]:
a["4"]=4
a

{'1': 1, '2': 2, '4': 4}

In [15]:
import ray
from ray.rllib.agents.sac import sac
ray.shutdown()        
ray.init(ignore_reinit_error=True)
sharpes=[]
checkpoints=[]
model_config=sac.DEFAULT_CONFIG.copy()

/home/sunshuo/miniconda3/envs/FinRL/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/sunshuo/miniconda3/envs/FinRL/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/sunshuo/miniconda3/envs/FinRL/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/sunshuo/miniconda3/envs/FinRL/lib/pyt

In [16]:
model_config

{'num_workers': 0,
 'num_envs_per_worker': 1,
 'create_env_on_driver': False,
 'rollout_fragment_length': 1,
 'batch_mode': 'truncate_episodes',
 'gamma': 0.99,
 'lr': 0.0001,
 'train_batch_size': 256,
 'model': {'_use_default_native_models': False,
  '_disable_preprocessor_api': False,
  '_disable_action_flattening': False,
  'fcnet_hiddens': [256, 256],
  'fcnet_activation': 'tanh',
  'conv_filters': None,
  'conv_activation': 'relu',
  'post_fcnet_hiddens': [],
  'post_fcnet_activation': 'relu',
  'free_log_std': False,
  'no_final_linear': False,
  'vf_share_layers': True,
  'use_lstm': False,
  'max_seq_len': 20,
  'lstm_cell_size': 256,
  'lstm_use_prev_action': False,
  'lstm_use_prev_reward': False,
  '_time_major': False,
  'use_attention': False,
  'attention_num_transformer_units': 1,
  'attention_dim': 64,
  'attention_num_heads': 1,
  'attention_head_dim': 32,
  'attention_memory_inference': 50,
  'attention_memory_training': 50,
  'attention_position_wise_mlp_dim': 32,
  

In [17]:
ray.__version__

'1.12.0'

In [3]:
c.update(a)
c

{'4': 4, '1': 1, '2': 2}

In [1]:
str(1)

'1'

In [ ]:
a={"1"}

In [2]:
"1,2,3,"+"2,3,4"

'1,2,3,2,3,4'

In [1]:
import numpy as np
np.array([1,2,3])[1:]

array([2, 3])

In [2]:
[1,2,3][1:]

[2, 3]

In [6]:
[[1]+[0]*24][-1]

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [1]:
import numpy as np
np.dot([1,2],[1,2])

5

In [6]:
list(np.array([1,2,3])*np.array([1,2,3]))+[1]

[1, 4, 9, 1]